Add rudimentary support for perplexity.ai API
danielmiessler/fabric pull request #1079
Opened 2024-10-24 19:55 UTC by destenson

## What this Pull Request (PR) does
Adds rudimentary support for perplexity.ai API.

Since perplexity doesn't support the endpoint to list the available models, the list had to be hard-coded for now.

To enable perplexity support, add the following to your Fabric config file:
`PERPLEXITY_API_KEY=pplx-xxxxx`

## Related issues
#1078 

## Screenshots
N/A

2024-10-25 21:09 UTC, eugeis requested changes
Hi, thank you for the PR.

Please check my todo in get models method, it is easy to implement,  just copy/paste config part from Azure vendor.

P.S: btw. you don't need manually to add the key in the .env file.  It will be automatically availablr as part of setup procedure.

2024-10-27 22:49 UTC, closed without merging

2024-10-28 11:28 UTC, eugeis commented
Hi @destenson, you closed the PR, don't want to have it anymore?

2024-10-29 02:17 UTC, destenson commented
When I tried to use actually it, it "worked" but gave really bad responses, mostly gibberish. And I don't have time or desire to try to fix it. Groq usually works really well for me.

2024-10-29 08:10 UTC, eugeis commented
ok