Add dry run
danielmiessler/fabric pull request #892
Opened 2024-08-29 10:46 UTC by kanaqsasak

# Pull Request Description

## Summary
This pull request introduces a new `--dry-run` flag to the CLI application. This flag allows users to see what would be sent to the model without actually sending the request. The changes include updates to the `README.md` for documentation purposes and modifications to the CLI code to implement the dry-run functionality.

## Files Changed
1. **README.md**
   - Added a description for the new `--dry-run` flag under the Application Options section.

2. **cli/cli.go**
   - Implemented the logic for handling the `--dry-run` flag. This includes fetching the pattern and context content (if provided) and displaying the formatted request that would be sent to the model.

3. **cli/flags.go**
   - Added the `DryRun` field to the `Flags` struct to accommodate the new command-line option.

## Code Changes

### README.md
```diff
 Application Options:
   -u, --url=              Choose ollama url (default: http://127.0.0.1:11434)
   -o, --output=           Output to file
   -n, --latest=           Number of latest patterns to list (default: 0)
+      --dry-run           Show what would be sent to the model without actually sending it
```

### cli/cli.go
```diff
 func Cli() (message string, err error) {
 		}
 	}

+	if currentFlags.DryRun {
+		var patternContent string
+		var contextContent string
+
+		if currentFlags.Pattern != "" {
+			pattern, patternErr := fabric.Db.Patterns.GetPattern(currentFlags.Pattern)
+			if patternErr != nil {
+				fmt.Printf("Error getting pattern content: %v\n", patternErr)
+				return "", patternErr
+			}
+			patternContent = pattern.Pattern // Assuming the content is stored in the 'Pattern' field
+		}
+
+		if currentFlags.Context != "" {
+			context, contextErr := fabric.Db.Contexts.GetContext(currentFlags.Context)
+			if contextErr != nil {
+				fmt.Printf("Error getting context content: %v\n", contextErr)
+				return "", contextErr
+			}
+			contextContent = context.Content
+		}
+
+		systemMessage := strings.TrimSpace(contextContent) + strings.TrimSpace(patternContent)
+		userMessage := strings.TrimSpace(currentFlags.Message)
+
+		fmt.Println("Dry run: Would send the following request:\n")
+		if systemMessage != "" {
+			fmt.Printf("System:\n%s\n\n", systemMessage)
+		}
+		if userMessage != "" {
+			fmt.Printf("User:\n%s\n", userMessage)
+		}
+		return "", nil
+	}
```

### cli/flags.go
```diff
 type Flags struct {
 	YouTube                 string  `short:"y" long:"youtube" description:"YouTube video url to grab transcript, comments from it and send to chat"`
 	YouTubeTranscript       bool    `long:"transcript" description:"Grab transcript from YouTube video and send to chat"`
 	YouTubeComments         bool    `long:"comments" description:"Grab comments from YouTube video and send to chat"`
+	DryRun                  bool    `long:"dry-run" description:"Show what would be sent to the model without actually sending it"`
 }
```

## Reason for Changes
The `--dry-run` flag is introduced to provide users with a way to preview the request that would be sent to the model. This can be useful for debugging and ensuring that the correct data is being sent without making an actual request.

## Impact of Changes
- **Functionality**: Adds a new feature allowing users to perform a dry run of their request.
- **Usability**: Improves the user experience by providing a way to verify requests before sending them.
- **Codebase**: Introduces additional conditional logic to handle the `--dry-run` flag.

## Test Plan
- Manually test the `--dry-run` flag with various combinations of patterns, contexts, and messages to ensure the correct output is displayed.
- Verify that the application behaves as expected when the `--dry-run` flag is not used.

## Additional Notes
- Ensure that any existing automated tests that may interact with the CLI are updated to account for the new `--dry-run` functionality.
- Consider adding automated tests specifically for the `--dry-run` feature in future updates.

2024-08-29 17:04 UTC, eugeis commented
Thank you, for the implementation.

Please refactor and integrate it to the Chatter struct:

...
var chatter *core.Chatter
	if chatter, err = fabric.GetChatter(currentFlags.Model, currentFlags.Stream, currentFlags.DryRun); err != nil {
		return
	}
....

type Chatter struct {
	db *db.Db

	Stream bool
	DryRun bool

	model  string
	vendor vendors.Vendor
}


And use the field DryRun in the methods of the Chatter struct to print out instead of sending the request.

2024-09-01 07:05 UTC, kanaqsasak commented
@eugeis I've refactored the dry run to a DryRun vendor as requested and ensured that the dry run model is excluded when listing models.

Let me know if there's anything else you'd like to adjust.

2024-09-01 13:57 UTC, eugeis requested changes
Great, please apply those two comments and we would be ready to merge.

2024-09-01 13:57 UTC, eugeis commented on core/fabric.go
> +		gemini.NewClient(), anthropic.NewClient(), dryrun.NewClient())
We don't need to register the DryRun Vendor, because it is controlled directly by the separated dryRun flag. Please revert this changes.

2024-09-01 13:57 UTC, eugeis commented on core/models.go
>  func (o *VendorsModels) AddVendorModels(vendor string, models []string) {
We don't need to register the DryRun Vendor so it shall not be added to this manager. Please revert this changes.

2024-09-03 09:07 UTC, merged